#!/bin/bash
## file : appendfonts

appendfonts() {
	## Clear out the current contents.
	sed '/\/\/--APPENDFONTS-MARKER--/,$d' $1 > appendfonts.tmp

	echo -e "//--APPENDFONTS-MARKER--\n; // fix semi-colon insertion bug" >> appendfonts.tmp

	cat fonts/*-desc.js >> appendfonts.tmp
	echo 'if (bwipjs_fonts.onready) { bwipjs_fonts.onready.call(null); }' >> appendfonts.tmp

	mv -f appendfonts.tmp $1
}

appendfonts browser-fonts.js
appendfonts lib/xhr-fonts.js

