#!/bin/bash
## file: imgtest
##
## usage: imgtest [--refresh] symbol text opts
##
## Compare a generated image against a proof image.
##
REGEN=NO
if [ "x$1" == x--refresh ] ; then
	REGEN=YES
	shift
fi

sym="$1"
text="$2"
opts="$3"

## Generate a safe file name
filename=$(echo "$sym $text $opts" | sed -e 's/[^a-zA-Z0-9]/-/g' -e 's/^--*//' -e 's/--*$//').png
 
echo "$sym ($text) ($opts) ..."

./genimg $sym "$text" $opts tests/$filename > /dev/null

if [ ! -f proofs/$filename -o $REGEN == YES ] ; then
	mv -f tests/$filename proofs/$filename
	exit 0
else
	perceptualdiff proofs/$filename tests/$filename
	exit $?
fi

