#!/bin/bash
##
## file : bwipjs/imgtests
##
## Top-level image comparision test driver
##
## Usage:  ./imgtests [--regen] [pattern]
##
## If --regen, then the proof images will be regenerated.
##
## Pattern (fixed substring) will only run tests for the matching barcode
## type(s).
##

PAT=
OPTS=
if [ "x$1" == x--regen ] ; then
    OPTS="$1"
    shift
fi
if [ "x$1" != x ] ; then
    PAT="$1"
    shift
fi

##
## Clear out previous runs
##
rm -f tests/*.png 2>/dev/null

## Capture all output to a log file
{

##
## Test number seed
##
let NTESTS=0
let NFAILS=0

## run level encoder text opts
function run() {
    if [[ $2 == *$PAT* ]] ; then
        ./imgtest $OPTS $2 "$3" "$4"
        if [ $? != 0 ] ; then
            ((NFAILS++))
        fi
        ((NTESTS++))
    fi
}

##
## Initialize the HTML output
##
cat <<@EOF > imgtests.html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" \>
<title>Image Tests</title>
<style type="text/css">
* {
    font:      11pt sans-serif;
}
h1 {
    font:      bold 14pt sans-serif;
}
div.main {
    padding-left:    1em;
    padding-bottom:  5px;
    white-space:     nowrap;
}
div.main ~ div.main {
    border-top: 2px solid #777;
}
div.error {
    background-color: rgba(255,0,0,.1);
}
div.main > div {
    display:        inline-block;
    white-space:    pre;
    padding:        10px;
    text-align:     center;
}
img, svg {
    padding: 1px;
    border:  1px solid blue;
}
span {
    padding:   5px;
}
.dot {
    width:          14px;
    height:         4px;
    border-radius:  7px;
    position:       fixed;
    right:          1px;
    background-color: #d00;
}
</style>
<script type="text/javascript">
window.addEventListener('load', () => {
    if (window.devicePixelRatio) {
        let sheet = document.styleSheets[0];
        sheet.insertRule('img, svg { zoom: ' + (1 / window.devicePixelRatio) + '; }');
    }
    window.addEventListener('resize', onresize);
    onresize();
});
function onresize() {
    let dots = document.body.querySelectorAll('div.dot');
    for (let i = 0; i < dots.length; i++) {
        document.body.removeChild(dots[i]);
    }

    let divs = document.body.querySelectorAll('div.main');
    let marks = [];
    for (let i = 0; i < divs.length; i++) {
        let div = divs[i];
        if (/error/.test(div.className)) {
            marks.push(div.offsetTop + div.offsetHeight / 2);
        }
    }

    // The 60 is height of up arrow + height of down arrow + height of 
    // bottom horizontal scrollbar.  Roughly.
    let mult = (window.innerHeight - 60) / document.body.offsetHeight;
    for (let i = 0; i < marks.length; i++) {
        let mark = marks[i];
        let dot = document.createElement('div');
        dot.className = 'dot';
        dot.style.top = (mark*mult + 20) + 'px';
        document.body.appendChild(dot);
    }
}
</script>
</head>
<body>
@EOF

##
## Run the test cases
##
. runbwipp

##
## Finish the html
##
cat <<@EOF >> imgtests.html
</body>
</html>
@EOF

##
## END OF TEST CASES
##
echo
echo "-----------------------"
echo "Number of tests: $NTESTS"
echo "Number of failures: $NFAILS"
echo "-----------------------"
echo

} | tee imgtests.log 2>&1

echo "Use imgtests.html to view results"
echo "Test output saved to imgtests.log"
exit 0
