#!/bin/bash
##
## file : bwipjs/imgtests
##
## Top-level image comparision test driver
##
## Usage:  ./imgtests [--regen] [pattern]
##
## If --regen, then the proof images will be regenerated.
##
## Pattern (fixed substring) will only run tests for the matching barcode
## type(s).
##

PAT=
OPTS=
if [ "x$1" == x--regen ] ; then
    OPTS="$1"
    shift
fi
if [ "x$1" != x ] ; then
    PAT="$1"
    shift
fi

##
## Clear out previous runs
##
rm -f tests/*.png 2>/dev/null

##
## Test number seed
##
let NTESTS=0
let NFAILS=0

## run level encoder text opts
function run() {
    if [[ $2 == *$PAT* ]] ; then
        ./imgtest $OPTS $2 "$3" "$4"
        if [ $? != 0 ] ; then
            ((NFAILS++))
        fi
        ((NTESTS++))
    fi
}

##
## Initialize the HTML output
##
cat <<@EOF > imgtests.html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" \>
<title>Image Tests</title>
<style type="text/css">
* {
    font:      11pt sans-serif;
}
h1 {
    font:      bold 14pt sans-serif;
}
div.main {
    padding-left:    1em;
    padding-bottom:  5px;
}
div.main ~ div.main {
    border-top: 2px solid #777;
}
div.error {
    background-color: rgba(255,0,0,.1);
}
div.main > div {
    display:        inline-block;
    white-space:    pre;
    padding:        10px;
    text-align:     center;
}
img {
    padding: 1px;
    border:  1px solid blue;
}
span {
    padding:   5px;
}
</style>
<script type="text/javascript">
window.addEventListener('load', () => {
    if (window.devicePixelRatio) {
        let sheet = document.styleSheets[0];
        sheet.insertRule('img { zoom: ' + (1 / window.devicePixelRatio) + '; }');
    }
});
</script>
</head>
<body>
@EOF

##
## Run the test cases
##
. runbwipp

##
## Finish the html
##
cat <<@EOF >> imgtests.html
</body>
</html>
@EOF

##
## END OF TEST CASES
##
echo 
echo "-----------------------"
echo "Number of tests: $NTESTS"
echo "Number of failures: $NFAILS"
echo "-----------------------"
echo
echo "imgtests.html to view results"

