#!/bin/bash
## bwip-js/develop/psc
##
## The master script for cross-compiling barcode.ps into src/bwipp.js.

## 7-Zip annoyance
chmod -x barcode.ps

##
## Create the lookup function
##
(
echo 'function bwipp_lookup(symbol) {'
echo '  if (!symbol) { throw new Error("bwipp.undefinedEncoder: bcid is not defined"); }'
echo '  switch (symbol.replace(/-/g, "_")) {'
grep -E '% --BEGIN ENCODER .*--' barcode.ps | sort -u |\
    sed -e 's/^.*BEGIN ENCODER \(.*\)--.*/    case "\1":return bwipp_\1;/' -e 's/-/_/g'
echo '  }'
echo '  throw new Error("bwipp.unknownEncoder: unknown encoder name: " + symbol);'
echo '}'
) > barcode-lookup.js

##
## Create the symbol list
##
(
echo 'var bwipp_symlist = ['
grep -E '% --BEGIN ENCODER|% --DESC:|% --EXAM:|% --EXOP:' barcode.ps |
    sed -e 's/% --BEGIN ENCODER\s*\(.*\)--/  { bcid:"\1"/'\
        -e 's/% --DESC:\s*\(.*\)/, desc:"\1"/'\
        -e 's/% --EXAM:\s*\(.*\)/, text:"\1"/'\
        -e 's/% --EXOP:\s*\(.*\)/, opts:"\1" },/'\
        -e 's/height=0.5/height=12.5/' |
    awk '{r = r $0} NR%4 == 0 {print r; r = ""}'
echo "];";
) > barcode-symlist.js

##
## Check for changes in the custom modules.
## Any file with a .bwipp suffix will be watched.
##
let diffs=0
for file in $(cd custom; ls *.bwipp) ; do
    name=$(basename -s .bwipp $file)
    ## BeginResource contains variable data
    sed -n "/% --BEGIN [A-Z]* $name--/,/% --END [A-Z]* $name--/{//!p}" barcode.ps | grep -vF '%%BeginResource:' > /tmp/$file
    diff -q /tmp/$file custom/$file 1>/dev/null
    if [ $? != 0 ] ; then
        let diffs=diffs+1
        echo "!!! BEGIN $name CHANGES"
        diff /tmp/$file custom/$file
        echo "!!! END $name CHANGES"
    fi
done
if [ $diffs != 0 ] ; then
    echo 'BWIPP modules have changed.'
    echo 'New template files at /tmp/*.bwipp'
    for file in $(cd custom; ls *.bwipp) ; do
        md5sum /tmp/$file custom/$file
    done
    exit 0
fi
rm -f /tmp/*.bwipp

##
## Replace the custom modules
##
PSFUNCS=
cp barcode.ps barcode.tmp
for name in $(cd custom; ls *.ps | sed -e 's/\.ps//') ; do
    echo replacing $name...
    sed -e "/^% --BEGIN [A-Z]* $name--/,/^% --END [A-Z]* $name--/s/^/%psc /" barcode.tmp > barcode.psc
    mv -f barcode.psc barcode.tmp
    PSFUNCS="$PSFUNCS $name"
done

(
echo '// Automatically generated by psc'
echo 'const PSFUNCS = "'$PSFUNCS'".trim().split(/ /g);'
) > psc-funcs.js


##
## Run the preprocessing pass
##
cat barcode.tmp custom/*.ps > barcode.psc
cp barcode.psc barcode.tmp
node psc-pre.js
if [ $? != 0 ] ; then
    exit 1
fi

##
## Update pscdbg.html
##
(
sed -e '/^<pre/q' pscdbg.html
##nl -s '| ' -b a barcode.psc
cat barcode.psc | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' | sed -e 's,.*,<code>&</code>,'
tac pscdbg.html | sed -e '/^<\/pre>/q' | tac
) > pscdbg.tmp
mv pscdbg.tmp pscdbg.html

##
## Cross-compile barcode.psc into barcode.pjs
##
echo "compiling..."
rm -f barcode.pjs 2> /dev/null

node <<@EOF
const fs  = require('node:fs');
const PSOPS = require('./psc-opers.js');
const PSLEX = require('./psc-lex.js');
const PSFUNCS = "$PSFUNCS".trim().split(' ');
const PSC = require('./psc.js');
const pstext = fs.readFileSync('barcode.psc', 'binary');
const flags  = "$*".split(' ');
try {
    const code = PSC(pstext, flags)
        .replace(/function bwipp_ren(?:linear|matrix|maximatrix)[()\\s{]+/g, (\$0) => {
            return \$0 + 'if (\$_.bwipjs_rawstack) {\\n' +
                   '\$_.bwipjs_rawstack.push(\$k[--\$j]); return;\\n' +
                   '}\\n';
        });
    fs.writeFileSync('barcode.pjs', code, 'binary');
} catch (e) {
    console.log(e.stack || e);
    process.exit(1);
}
@EOF

if [ ! -f barcode.pjs ] ; then
    exit 1
fi

##
## Peephole optimize barcode.pjs -> barcode.js
##
echo "optimizing..."
rm -f barcode.js 2> /dev/null
node optimize.mjs

if [ ! -f barcode.js ] ; then
    exit 1
fi

echo "finalizing..."
js-beautify --preserve-newlines barcode.js > bwipp.js

##
## Get the BWIPP version (date)
##
BWIPP_VERSION=$(grep '% Barcode Writer in Pure PostScript - Version' barcode.ps | sed -e 's/.*Version\s*//')
if [ "x$BWIPP_VERSION" = x ] ; then
    echo "Unable to find the version string in barcode.ps" 1>&2
    exit 1
fi

##
## Verify we can find the BWIPP copyright notice
##
COPYR=$(grep '% Copyright (c)' barcode.ps | sed -e 's,%,//,')
if [ "x$COPYR" = x ] ; then
    echo "Unable to find the copyright notice in barcode.ps" 1>&2
    exit 1
fi

##
## Verify we can find the BWIPP file version
##
FILEV=$(grep '% Barcode Writer in Pure PostScript - Version' barcode.ps | sed -e 's,%,//,')
if [ "x$FILEV" = x ] ; then
    echo "Unable to find the version string in barcode.ps" 1>&2
    exit 1
fi

## What year is it?
YEAR="2011-$(date +%Y)"

##
## Build the raw (unformatted, unminified) version of bwipp.js.
##
cat <<@EOF > bwipp.js
// bwip-js // Barcode Writer in Pure JavaScript
// https://github.com/metafloor/bwip-js
//
// This code was automatically generated from:
$FILEV
//
// Copyright (c) $YEAR Mark Warren
$COPYR
//
// Licensed MIT. See the LICENSE file in the bwip-js root directory.
$(cat barcode-hdr.js barcode.js barcode-ftr.js barcode-lookup.js barcode-symlist.js)
var BWIPP_VERSION = '$BWIPP_VERSION';

@EOF

js-beautify --preserve-newlines bwipp.js > src/bwipp.js

## js-beautify does not put a ending newline on the file
echo "" >> src/bwipp.js

##
## Clean up.  Separate commands so they can be commented out when debugging.
##
rm -f barcode.tmp  ## PS code after custom modules
##rm -f barcode.psc  ## PS code after preprocessing
rm -f barcode-lookup.js
rm -f barcode-symlist.js
##rm -f barcode.pjs  ## JS code output by psc.js
##rm -f barcode.js   ## JS code after optimzing
rm -f bwipp.js     ## JS code after branding

echo "success!"
exit 0
