// Automatically generated by psc
const PSFUNCS = " channelcode fifocache grouptextoptions inittextoptions processoptions raiseerror rendertext renlinear renmatrix renmaximatrix validatetext".trim().split(/ /g);
