// Automatically generated by psc
const PSFUNCS = " channelcode fifocache grouptextoptions inittextoptions processoptions raiseerror renderguards rendertext renlinear renmatrix renmaximatrix validatetext".trim().split(/ /g);
