#!/usr/bin/node

const bwipjs = require('./dist/bwip-js-node.js');

var syms = bwipjs.symbolList.slice();

const SYMITERS = 50;
let   symiters = 0;
let   runiters = 5;

function render(index) {
    let bcid = syms[index].bcid;
    let options = {
            bcid:bcid,
            text:syms[index].text,
        };
    let opts = syms[index].opts.split(' ');
    for (let i = 0; i < opts.length; i++) {
        let s = opts[i];
        let eq = s.indexOf('=');
        if (eq == -1) {
            options[s] = true;
        } else {
            options[s.substr(0, eq)] = s.substr(eq+1);
        }
    }

    try {
        bwipjs.toBuffer(options, (err, png) => {
                if (err) {
                    console.log(bcid, ': ' + err);
                    process.exit(1);
                } else {
                    console.log(bcid, ': ' + index + ' of ' + runiters);
                }
                if (++symiters < SYMITERS) {
                    render(index);
                } else if (++index < syms.length) {
                    symiters = 0;
                    render(index);
                } else if (--runiters > 0) {
                    symiters = 0;
                    render(0);
                } else {
                    console.log('done');
                }
            });
    } catch (e) {
        console.log(bcid, ': ' + e);
    }
}

render(0);
