#!/bin/bash

for dir in $(cd ../node_modules; ls -d bwipjs-*) ; do
    vers=${dir:7}
    echo "running version $vers ..."
    node benchmark.js --use-v$vers
    mv bench-v$vers.json bench-stats
done

echo "running current version ..."
node benchmark.js
mv bench-latest.json bench-stats

node bench-md.js
echo "benchmark.md to view results"
