#!/bin/bash
##
## file : bwipjs/runtests
##
## Top-level test driver.
##
## Usage:  ./runtests [level] [pattern]
##
## Level is optional and defaults to 0 (fewest tests)
##
## Pattern (fixed substring) will only run tests for the matching barcode
## type(s).
##
LVL=0
PAT=

if [[ "x$1" =~ ^x[0-9]$ ]] ; then
	LVL=$1
	shift
fi
if [ "x$1" != x ] ; then
	PAT="$1"
	shift
fi

##
## Clear out previous runs
##
rm -f tests/*.gsout tests/*.jsout 2>/dev/null
##rm -f coverage/* 2>/dev/null

##
## Create a special barcode.ps that has empty renderers for ghostscript
##
sed -e '/\/ren\w* {\s*$/,/^} bind def\s*$/s/^\s/% /' barcode.ps > tests/barcode.ps

##
## Test number seed
##
let TNO=0
let NTESTS=0
let NFAILS=0

function run() {
	if [[ $1 == *$PAT* ]] ; then
		./runtest $TNO $1 "$2" "$3"
		if [ $? != 0 ] ; then
			((NFAILS++))
		fi
		((NTESTS++))
	fi
	((TNO++))
}

##
## The test cases
##
run ean5 "90200" "includetext guardwhitespace"
run ean5 "90200" "textyoffset=52"
run ean5 "900" ""		## ERROR
run ean5 "ABCDE" ""		## ERROR
run ean2 "05" "includetext guardwhitespace"
run ean2 "05" "textyoffset=52"
run ean2 "90200" ""		## ERROR
run ean2 "AB" ""		## ERROR
run ean13 "2112345678900" "guardwhitespace"
run ean13 "2112345678900 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run ean13 "21123456789" ""  ## ERROR length
run ean13 "21123A5678900" "" ## ERROR bad character
run ean13 "2112345678900 0" "" ## ERROR bad addon length
run ean13 "2112345678901" "" ## ERROR bad check digit
run ean8 "02345673" ""
run ean8 "02345673 12" ""
run ean8 "02345673 12345" ""
run ean8 "02345673 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run ean8 "023456744" "" ## ERROR length
run ean8 "02345674" "" ## ERROR bad check digit
run ean8 "0234A673" "" ## ERROR bad character
run ean8 "02345673 023" "" ## ERROR bad addon length
run upca "01234565" "includetext guardwhitespace"
run upca "0123455" "includetext guardwhitespace"
run upca "0123454" "includetext guardwhitespace"
run upca "0123453" "includetext guardwhitespace"
run upca "0123452" "includetext guardwhitespace"
run upca "0123451" "includetext guardwhitespace"
run upca "0123450" "includetext guardwhitespace"
run upca "416000336108" ""
run upca "416000336108 01" ""
run upca "416000336108 01234" ""
run upca "416000336108 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run upca "4160003361079" ""	## ERROR length
run upca "416000336107" ""	## ERROR bad check digit
run upca "416000A36108" ""  ## ERROR bad character
run upca "0123A565" ""  ## ERROR bad character
run upca "416000336108 000" ""	## ERROR bad addon length
run upca "3123456" "" ## ERROR bad number system
run upce "00123457" ""
run upce "0123456" "includetext"
run upce "01234000005" ""
run upce "01230000045" ""
run upce "01220000345" ""
run upce "01210000234" ""
run upce "01200000123" ""
run upce "012345000065" ""
run upce "012345000065 01" ""
run upce "012345000065 01234" ""
run upce "012345000065 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run upce "00127" ""  ## ERROR bad length
run upce "01234A00006" "" ## ERROR bad character
run upce "001A3457" "" ## ERROR bad character
run upce "00123458" "" ## ERROR bad check digit
run upce "012345000065 012" "" ## ERROR bad addon length
run upce "3012345" "" ## ERROR bad number system
run isbn "81-7525-766-0" ""	 
run isbn "978-1-56581-231-4" ""
run isbn "978-1-56581-231-4 52250" "includetext guardwhitespace isbntextxoffset=13 isbntextyoffset=75"
run isbn "978-1-56581-2314" ""	## ERROR bad length
run isbn "978-1-56581-231-4 333" ""	## ERROR bad addon length
run isbn "970-1-56581-231-4" ""	## ERROR bad prefix
run isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run isbn "978-1-5658--231-4" ""	## ERROR adjacent dashes
run isbn "978-1-565-8-231-4" ""	## ERROR bad number of dashes/digits
run isbn "978-1-56581-23--4" ""	## ERROR character 14 must be a digit
run isbn "978-1-56581-2314-" ""	## ERROR penultimate must be a dash
run isbn "978-1-56581-231--" ""	## ERROR final must be a digit
run isbn "-17525766-0" ""	## ERROR first must be a digit
run isbn "817525766-0" ""	## ERROR bad number of dashes/digits
run isbn "817--5766-0" ""	## ERROR adjacent dashes
run isbn "817525-76---0" ""		## character 11 must be a digit 
run isbn "817525-76-770" ""		## penultimate must be a dash
run isbn "81-7525-766-7" ""		## bad check digit
run isbn "81-7525-766--" ""		## final must be a digit
run ismn "M-2605-3211-3" ""
run ismn "979-0-2605-3211-3" "includetext guardwhitespace"
run ismn "979-0-2605-3211-3 12345" "includetext guardwhitespace"
run issn "0311-175X 00 17" "includetext guardwhitespace"
run code128 "Count01234567!" "includetext"
run code128 "^0270123^027" "parse"
run code128 "0123^0277890" "parse"
run code128 "ABC^0270123" "parse"
run code128 "Panam^225" "parse"
run code128 "^FNC1890^^ABC" "parsefnc"  ## ESCAPED ^
run code128 "^FNC3ABCD^FNC2" "parsefnc"
run code128 "^104^102^016^017^033^034^035" "raw"
run gs1-128 "(01)95012345678903(3103)000123" "includetext"
run gs1-128 "(01)0061414199996(17)100101(10)123ABC(21)1234567890" ""
run ean14 "(01) 0 46 01234 56789 3" "includetext"
run sscc18 "(00) 0 0614141 123456789 0" "includetext"
run sscc18 "(00)00614141123456789" "includetext"
run code39 "THIS IS CODE 39" "includetext hidestars"
run code39 "THIS IS CODE 39" "includetext includecheck includecheckintext"
run code39 "THIS IS CODE 39Q" "includetext includecheck validatecheck hidestars"
run code39 "ABCa0123" ""  ## ERROR bad character
run code39 "THIS IS CODE 39R" "includecheck validatecheck" ## ERROR bad check
run code39ext "Code39 Ext!" "includetext includecheck includecheckintext"
run code32 "01234567" "includetext"
run pzn "123456" "includetext"
run code93 "THIS IS CODE 93" "includetext includecheck"
run code93ext "Code93 Ext!" "includetext includecheck"
run interleaved2of5 "2401234567" "height=0.5 includecheck includetext includecheckintext"
run itf14 "0 46 01234 56789 3" "includetext"
run itf14 "0460123456789" "includetext"
run identcode "563102430313" "includetext"
run leitcode "21348075016401" "includetext"
run databaromni "(01)24012345678905" ""
run databarstacked "(01)24012345678905" ""
run databarstackedomni "(01)24012345678905" ""
run databartruncated "(01)24012345678905" ""
run databarlimited "(01)15012345678907" ""
run databarexpanded "(01)95012345678903(3103)000123" ""
run databarexpandedstacked "(01)95012345678903(3103)000123" "segments=4"
run pharmacode "117480" "showborder"
run pharmacode2 "117480" "includetext showborder"
run code2of5 "01234567" "includetext"
run code2of5 "01234567" "includetext includecheck includecheckintext"
run code2of5 "012345670" "includetext includecheck validatecheck"
run code2of5 "01234567A" ""  ## ERROR bad char
run code2of5 "012345671" "validatecheck"  ## ERROR bad check
run industrial2of5 "01234567" "includetext includecheck includecheckintext"
run iata2of5 "01234567" "includetext includecheck includecheckintext"
run matrix2of5 "01234567" "includetext includecheck includecheckintext"
run coop2of5 "01234567" "includetext includecheck includecheckintext"
run datalogic2of5 "01234567" "includetext includecheck includecheckintext"
run code11 "0123456789" "includetext includecheck includecheckintext"
run bc412 "BC412" "semi includetext includecheckintext"
run rationalizedCodabar "A0123456789B" "includetext includecheck includecheckintext"
run onecode "0123456709498765432101234567891" "barcolor=FF0000"
run postnet "01234" "includetext includecheckintext"
run planet "01234567890" "includetext includecheckintext"
run royalmail "LE28HS9Z" "includetext includecheckintext"
run royalmail "LE28HS9Z9" "includetext validatecheck"
run royalmail "LE28HS9ZA" "includetext validatecheck" ## ERROR bad check
run auspost "1156439111ABA 9" "includetext custinfoenc=character"
run auspost "4556439111ABA 9" "includetext custinfoenc=character"
run auspost "5956439111ABA 9" "includetext custinfoenc=character"
run auspost "6256439111234567890123456" "includetext custinfoenc=numeric"
run kix "1231FZ13XHS" "includetext"
run japanpost "6540123789-A-K-Z" "includetext includecheckintext"
run msi "0123456789" "includetext includecheck includecheckintext"
run msi "0123456789" "includetext includecheck checktype=mod11"
run msi "0123456789" "includetext includecheck checktype=mod1010"
run msi "0123456789" "includetext includecheck checktype=mod1110"
run msi "0123456789" "includetext includecheck checktype=ncrmod11"
run msi "0123456789" "includetext includecheck checktype=ncrmod1110"
run plessey "01234ABCD" "includetext includecheckintext"
run telepen "ABCDEF" "includetext"
run telepennumeric "01234567" "includetext"
run posicode "ABC123" "version=b inkspread=-0.5 parsefnc includetext"
run codablockf "CODABLOCK F 34567890123456789010040digit" "columns=8"
run code16k "Abcd-1234567890-wxyZ" ""
run code49 "MULTIPLE ROWS IN CODE 49" ""
run channelcode "3493" "height=0.5 includetext "
run flattermarken "11099" "inkspread=-0.25 showborder borderleft=0 borderright=0"
run raw "331132131313411122131311333213114131131221323" "height=0.5"
run daft "FATDAFTDAD" ""
run symbol "fima" ""
run symbol "fimb" ""
run symbol "fimc" ""
run symbol "fimd" "backgroundcolor=DD000011"
run symbol "fime" ""	## ERROR unknown symbol
run pdf417 "This is PDF417" "columns=2"
run pdf417compact "This is compact PDF417" "columns=2"
run micropdf417 "MicroPDF417" ""
run datamatrix "This is Data Matrix!" ""
run datamatrixrectangular "1234" ""
run qrcode "http://goo.gl/0bis" "eclevel=M"
run qrcode "QR CODE 1234" "version=1 eclevel=L"
run qrcode "QR CODE 1234" "version=2 eclevel=M"
run qrcode "QR CODE 1234" "version=3 eclevel=Q"
run qrcode "QR CODE 1234" "version=4 eclevel=H"
run qrcode "QR Code" ""
run qrcode "QR ^067ode" "parse"
run qrcode "QR CODE 7890" "format=micro"
run qrcode "QR CODE 7890" "format=any"
run qrcode "QR CODE 7890" "format=full"
run qrcode "QR CODE 7890" "format=micro eclevel=L"
run qrcode "QR CODE 7890" "format=micro eclevel=M"
run qrcode "QR CODE 7890" "format=micro eclevel=Q"	## raiseerror
run microqrcode "1234" ""
run maxicode "[)>^03001^02996152382802^029840^029001^0291Z00004951^029UPSN^02906X610^029159^0291234567^0291/1^029^029Y^029634 ALPHA DR^029PITTSBURGH^029PA^029^004" "mode=2 parse"

run azteccode "This is Aztec Code" "format=full"
run azteccode "This is ^065ztec Code" "parse"
run azteccode "This is Aztec Code" "eclevel=1"
run azteccode "This is Aztec Code" "eclevel=25"
run azteccode "This is Aztec Code" "eclevel=50"
run azteccode "This is Aztec Code" "eclevel=75"
run azteccode "This is Aztec Code" "eclevel=99"

## The format=value is added to get branch coverage
run azteccodecompact "1234" ""
run azteccodecompact "1234" "format=compact"
run aztecrune "0" ""
run aztecrune "1" "format=rune"
if [ $LVL -ge 9 ] ; then
	## Only run these when exhaustive testing
	for RUNE in {2..255} ; do
		run aztecrune $RUNE ""
	done
fi

run codeone "Code One" ""
run hanxin "This is Han Xin" ""
run dotcode "This is DotCode" "fast"
run gs1-cc "(01)95012345678903(3103)000123" "ccversion=b cccolumns=4"
run ean13composite "2112345678900|(99)1234-abcd" "includetext"
run ean8composite "02345673|(21)A12345678" "includetext"
run upcacomposite "416000336108|(99)1234-abcd" "includetext"
run upcecomposite "00123457|(15)021231" "includetext"
run databaromnicomposite "(01)03612345678904|(11)990102" ""
run databarstackedcomposite "(01)03412345678900|(17)010200" ""
run databarstackedomnicomposite "(01)03612345678904|(11)990102" ""
run databartruncatedcomposite "(01)03612345678904|(11)990102" ""
run databarlimitedcomposite "(01)03512345678907|(21)abcdefghijklmnopqrstuv" ""
run databarexpandedcomposite "(01)93712345678904(3103)001234|(91)1A2B3C4D5E" ""
run databarexpandedstackedcomposite "(01)00012345678905(10)ABCDEF|(21)12345678" "segments=4 "
run gs1-128composite "(00)030123456789012340|(02)13012345678909(37)24(10)1234567ABCDEFG" "ccversion=c"
run gs1datamatrix "(01)03453120000011(17)120508(10)ABCD1234(410)9501101020917" ""
run gs1datamatrixrectangular "(01)03453120000011(17)120508(10)ABCD1234(410)9501101020917" ""
run gs1qrcode "(01)03453120000011(8200)http://www.abc.net(10)ABCD1234(410)9501101020917" ""
run hibccode39 "A123BJC5D6E71" "includetext"
run hibccode128 "A123BJC5D6E71" "includetext"
run hibcdatamatrix "A123BJC5D6E71" ""
run hibcdatamatrixrectangular "A123BJC5D6E71" ""
run hibcpdf417 "A123BJC5D6E71" ""
run hibcmicropdf417 "A123BJC5D6E71" ""
run hibcqrcode "A123BJC5D6E71" ""
run hibccodablockf "A123BJC5D6E71" ""
run hibcazteccode "A123BJC5D6E71" ""

##
## END OF TEST CASES
##
echo 
echo "-----------------------"
echo "Number of tests: $NTESTS"
echo "Number of failures: $NFAILS"
echo "-----------------------"

