#!/bin/bash
##
## file : bwipjs/runtests
##
## Top-level test driver.
##
## Usage:  ./runtests [level] [pattern]
##
## Level is optional and defaults to 0 (fewest tests)
##
## Pattern (fixed substring) will only run tests for the matching barcode
## type(s).
##
LVL=0
PAT=

if [[ "x$1" =~ ^x[0-9]$ ]] ; then
	LVL=$1
	shift
fi
if [ "x$1" != x ] ; then
	PAT="$1"
	shift
fi

##
## Clear out previous runs
##
rm -f tests/*.gsout tests/*.jsout 2>/dev/null
##rm -f coverage/* 2>/dev/null

##
## Create a special barcode.ps that has empty renderers for ghostscript
##
sed -e '/\/ren\w* {\s*$/,/^}/s/^\s/% /' barcode.ps > tests/barcode.ps

## Tests stats
let NTESTS=0
let NFAILS=0

## run lvl encoder text options
function run() {
	if (( $1 <= $LVL )) ; then
		if [[ $2 == *$PAT* ]] ; then
			./runtest $2 "$3" "$4"
			if [ $? != 0 ] ; then
				((NFAILS++))
			fi
			((NTESTS++))
		fi
	fi
}

## The zero-level test cases pulled directly from barcode.ps
. runbwipp

##
## The non-zero test cases
##
run 1 ean5 "90200" "textyoffset=52"
run 1 ean5 "900" ""		## ERROR
run 1 ean5 "ABCDE" ""	## ERROR
run 1 ean2 "05" "textyoffset=52"
run 1 ean2 "90200" ""	## ERROR
run 1 ean2 "AB" ""		## ERROR
run 1 ean13 "2112345678900 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 ean13 "21123456789" ""     ## ERROR length
run 1 ean13 "21123A5678900" ""   ## ERROR bad character
run 1 ean13 "2112345678900 0" "" ## ERROR bad addon length
run 1 ean13 "2112345678901" ""   ## ERROR bad check digit
run 1 ean8 "02345673 12" ""
run 1 ean8 "02345673 12345" ""
run 1 ean8 "02345673 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 ean8 "023456744" ""    ## ERROR length
run 1 ean8 "02345674" ""     ## ERROR bad check digit
run 1 ean8 "0234A673" ""     ## ERROR bad character
run 1 ean8 "02345673 023" "" ## ERROR bad addon length
run 1 upca "0123455" "includetext guardwhitespace"
run 1 upca "0123454" "includetext guardwhitespace"
run 1 upca "0123453" "includetext guardwhitespace"
run 1 upca "0123452" "includetext guardwhitespace"
run 1 upca "0123451" "includetext guardwhitespace"
run 1 upca "0123450" "includetext guardwhitespace"
run 1 upca "416000336108" ""
run 1 upca "416000336108 01" ""
run 1 upca "416000336108 01234" ""
run 1 upca "416000336108 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 upca "4160003361079" ""    ## ERROR length
run 1 upca "416000336107" ""	 ## ERROR bad check digit
run 1 upca "416000A36108" ""     ## ERROR bad character
run 1 upca "0123A565" ""         ## ERROR bad character
run 1 upca "416000336108 000" "" ## ERROR bad addon length
run 1 upca "3123456" ""          ## ERROR bad number system
run 1 upce "0123456" "includetext"
run 1 upce "01234000005" ""
run 1 upce "01230000045" ""
run 1 upce "01220000345" ""
run 1 upce "01210000234" ""
run 1 upce "01200000123" ""
run 1 upce "012345000065" ""
run 1 upce "012345000065 01" ""
run 1 upce "012345000065 01234" ""
run 1 upce "012345000065 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 upce "00127" ""  ## ERROR bad length
run 1 upce "01234A00006" "" ## ERROR bad character
run 1 upce "001A3457" "" ## ERROR bad character
run 1 upce "00123458" "" ## ERROR bad check digit
run 1 upce "012345000065 012" "" ## ERROR bad addon length
run 1 upce "3012345" "" ## ERROR bad number system
run 1 isbn "978-1-56581-231-4" ""
run 1 isbn "978-1-56581-231-4 52250" "includetext guardwhitespace isbntextxoffset=13 isbntextyoffset=75"
run 1 isbn "978-1-56581-2314" ""	## ERROR bad length
run 1 isbn "978-1-56581-231-4 333" ""	## ERROR bad addon length
run 1 isbn "970-1-56581-231-4" ""	## ERROR bad prefix
run 1 isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run 1 isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run 1 isbn "978-1-5658--231-4" ""	## ERROR adjacent dashes
run 1 isbn "978-1-565-8-231-4" ""	## ERROR bad number of dashes/digits
run 1 isbn "978-1-56581-23--4" ""	## ERROR character 14 must be a digit
run 1 isbn "978-1-56581-2314-" ""	## ERROR penultimate must be a dash
run 1 isbn "978-1-56581-231--" ""	## ERROR final must be a digit
run 1 isbn "-17525766-0" ""	## ERROR first must be a digit
run 1 isbn "817525766-0" ""	## ERROR bad number of dashes/digits
run 1 isbn "817--5766-0" ""	## ERROR adjacent dashes
run 1 isbn "817525-76---0" ""		## character 11 must be a digit 
run 1 isbn "817525-76-770" ""		## penultimate must be a dash
run 1 isbn "81-7525-766-7" ""		## bad check digit
run 1 isbn "81-7525-766--" ""		## final must be a digit
run 1 ismn "979-0-2605-3211-3" "includetext guardwhitespace"
run 1 ismn "979-0-2605-3211-3 12345" "includetext guardwhitespace"
run 1 issn "0311-175X 00 17" "includetext guardwhitespace"
run 1 code128 "^0270123^027" "parse"
run 1 code128 "0123^0277890" "parse"
run 1 code128 "ABC^0270123" "parse"
run 1 code128 "Panam^225" "parse"
run 1 code128 "^FNC1890^^ABC" "parsefnc"  ## ESCAPED ^
run 1 code128 "^FNC3ABCD^FNC2" "parsefnc"
run 1 code128 "^104^102^016^017^033^034^035" "raw"
run 1 code39 "THIS IS CODE 39" "includetext includecheck includecheckintext"
run 1 code39 "THIS IS CODE 39Q" "includetext includecheck validatecheck hidestars"
run 1 code39 "ABCa0123" ""  ## ERROR bad character
run 1 code39 "THIS IS CODE 39R" "includecheck validatecheck" ## ERROR bad check
run 1 itf14 "0460123456789" "includetext"
run 1 code2of5 "01234567" "includetext includecheck includecheckintext"
run 1 code2of5 "012345670" "includetext includecheck validatecheck"
run 1 code2of5 "01234567A" ""  ## ERROR bad char
run 1 code2of5 "012345671" "validatecheck"  ## ERROR bad check
run 1 royalmail "LE28HS9Z9" "includetext validatecheck"
run 1 royalmail "LE28HS9ZA" "includetext validatecheck" ## ERROR bad check
run 1 auspost "4556439111ABA 9" "includetext custinfoenc=character"
run 1 auspost "5956439111ABA 9" "includetext custinfoenc=character"
run 1 auspost "6256439111234567890123456" "includetext custinfoenc=numeric"
run 1 msi "0123456789" "includetext includecheck checktype=mod11"
run 1 msi "0123456789" "includetext includecheck checktype=mod1010"
run 1 msi "0123456789" "includetext includecheck checktype=mod1110"
run 1 msi "0123456789" "includetext includecheck checktype=ncrmod11"
run 1 msi "0123456789" "includetext includecheck checktype=ncrmod1110"
run 1 symbol "fima" ""
run 1 symbol "fimb" ""
run 1 symbol "fimc" ""
run 1 symbol "fimd" "backgroundcolor=DD000011"
run 1 symbol "fime" ""	## ERROR unknown symbol
run 1 qrcode "QR CODE 1234" "version=1 eclevel=L"
run 1 qrcode "QR CODE 1234" "version=2 eclevel=M"
run 1 qrcode "QR CODE 1234" "version=3 eclevel=Q"
run 1 qrcode "QR CODE 1234" "version=4 eclevel=H"
run 1 qrcode "QR Code" ""
run 1 qrcode "QR ^067ode" "parse"
run 1 qrcode "QR CODE 7890" "format=micro"
run 1 qrcode "QR CODE 7890" "format=full"
run 1 qrcode "QR CODE 7890" "format=micro eclevel=L"
run 1 qrcode "QR CODE 7890" "format=micro eclevel=M"
run 1 qrcode "QR CODE 7890" "format=micro eclevel=Q"	## raiseerror
run 1 azteccode "This is ^065ztec Code" "parse"
run 1 azteccode "This is Aztec Code" "eclevel=1"
run 1 azteccode "This is Aztec Code" "eclevel=25"
run 1 azteccode "This is Aztec Code" "eclevel=50"
run 1 azteccode "This is Aztec Code" "eclevel=75"
run 1 azteccode "This is Aztec Code" "eclevel=99"

## The format=value is added to get branch coverage
run 1 azteccodecompact "1234" "format=compact"
## Only run these when exhaustive testing
for RUNE in {2..255} ; do
	run 9 aztecrune $RUNE ""
done

run 1 gs1datamatrix "(01)02900001333399212v<t!6SWsA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==" ""

##
## END OF TEST CASES
##
echo 
echo "-----------------------"
echo "Number of tests: $NTESTS"
echo "Number of failures: $NFAILS"
echo "-----------------------"

