#!/bin/bash
##
## file : bwipjs/runtests
##
## Top-level test driver.
##
## Usage:  ./runtests [level] [pattern]
##
## Level is optional and defaults to 0 (fewest tests)
##
## Pattern (fixed substring) will only run tests for the matching barcode
## type(s).
##
LVL=0
PAT=

if [[ "x$1" =~ ^x[0-9]$ ]] ; then
	LVL=$1
	shift
fi
if [ "x$1" != x ] ; then
	PAT="$1"
	shift
fi

##
## Clear out previous runs
##
rm -f tests/*.gsout tests/*.jsout 2>/dev/null
##rm -f coverage/* 2>/dev/null

##
## Create a special barcode.ps that has empty renderers for ghostscript
##
sed -e '/\/ren\w* {\s*$/,/^}/s/^\s/% /' barcode.ps > tests/barcode.ps

## Tests stats
let NTESTS=0
let NFAILS=0

## run lvl encoder text options
function run() {
	if (( $1 <= $LVL )) ; then
		if [[ $2 == *$PAT* ]] ; then
			./runtest $2 "$3" "$4"
			if [ $? != 0 ] ; then
				((NFAILS++))
			fi
			((NTESTS++))
		fi
	fi
}

##
## The test cases
##
run 0 ean5 "90200" "includetext guardwhitespace"
run 0 ean5 "90200" "textyoffset=52"
run 1 ean5 "900" ""		## ERROR
run 1 ean5 "ABCDE" ""	## ERROR
run 0 ean2 "05" "includetext guardwhitespace"
run 0 ean2 "05" "textyoffset=52"
run 1 ean2 "90200" ""	## ERROR
run 1 ean2 "AB" ""		## ERROR
run 0 ean13 "2112345678900" "guardwhitespace"
run 0 ean13 "2112345678900 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 ean13 "21123456789" ""     ## ERROR length
run 1 ean13 "21123A5678900" ""   ## ERROR bad character
run 1 ean13 "2112345678900 0" "" ## ERROR bad addon length
run 1 ean13 "2112345678901" ""   ## ERROR bad check digit
run 0 ean8 "02345673" ""
run 0 ean8 "02345673 12" ""
run 0 ean8 "02345673 12345" ""
run 0 ean8 "02345673 12345" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 ean8 "023456744" ""    ## ERROR length
run 1 ean8 "02345674" ""     ## ERROR bad check digit
run 1 ean8 "0234A673" ""     ## ERROR bad character
run 1 ean8 "02345673 023" "" ## ERROR bad addon length
run 0 upca "01234565" "includetext guardwhitespace"
run 0 upca "0123455" "includetext guardwhitespace"
run 0 upca "0123454" "includetext guardwhitespace"
run 0 upca "0123453" "includetext guardwhitespace"
run 0 upca "0123452" "includetext guardwhitespace"
run 0 upca "0123451" "includetext guardwhitespace"
run 0 upca "0123450" "includetext guardwhitespace"
run 0 upca "416000336108" ""
run 0 upca "416000336108 01" ""
run 0 upca "416000336108 01234" ""
run 0 upca "416000336108 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 upca "4160003361079" ""    ## ERROR length
run 1 upca "416000336107" ""	 ## ERROR bad check digit
run 1 upca "416000A36108" ""     ## ERROR bad character
run 1 upca "0123A565" ""         ## ERROR bad character
run 1 upca "416000336108 000" "" ## ERROR bad addon length
run 1 upca "3123456" ""          ## ERROR bad number system
run 0 upce "00123457" ""
run 0 upce "0123456" "includetext"
run 0 upce "01234000005" ""
run 0 upce "01230000045" ""
run 0 upce "01220000345" ""
run 0 upce "01210000234" ""
run 0 upce "01200000123" ""
run 0 upce "012345000065" ""
run 0 upce "012345000065 01" ""
run 0 upce "012345000065 01234" ""
run 0 upce "012345000065 01234" "includetext addontextfont=OCR-B addontextsize=9 addontextxoffset=10 addontextyoffset=73"
run 1 upce "00127" ""  ## ERROR bad length
run 1 upce "01234A00006" "" ## ERROR bad character
run 1 upce "001A3457" "" ## ERROR bad character
run 1 upce "00123458" "" ## ERROR bad check digit
run 1 upce "012345000065 012" "" ## ERROR bad addon length
run 1 upce "3012345" "" ## ERROR bad number system
run 0 isbn "81-7525-766-0" ""	 
run 0 isbn "978-1-56581-231-4" ""
run 0 isbn "978-1-56581-231-4 52250" "includetext guardwhitespace isbntextxoffset=13 isbntextyoffset=75"
run 1 isbn "978-1-56581-2314" ""	## ERROR bad length
run 1 isbn "978-1-56581-231-4 333" ""	## ERROR bad addon length
run 1 isbn "970-1-56581-231-4" ""	## ERROR bad prefix
run 1 isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run 1 isbn "978-1-56581-231-5" ""	## ERROR bad check digit
run 1 isbn "978-1-5658--231-4" ""	## ERROR adjacent dashes
run 1 isbn "978-1-565-8-231-4" ""	## ERROR bad number of dashes/digits
run 1 isbn "978-1-56581-23--4" ""	## ERROR character 14 must be a digit
run 1 isbn "978-1-56581-2314-" ""	## ERROR penultimate must be a dash
run 1 isbn "978-1-56581-231--" ""	## ERROR final must be a digit
run 1 isbn "-17525766-0" ""	## ERROR first must be a digit
run 1 isbn "817525766-0" ""	## ERROR bad number of dashes/digits
run 1 isbn "817--5766-0" ""	## ERROR adjacent dashes
run 1 isbn "817525-76---0" ""		## character 11 must be a digit 
run 1 isbn "817525-76-770" ""		## penultimate must be a dash
run 1 isbn "81-7525-766-7" ""		## bad check digit
run 1 isbn "81-7525-766--" ""		## final must be a digit
run 0 ismn "M-2605-3211-3" ""
run 0 ismn "979-0-2605-3211-3" "includetext guardwhitespace"
run 0 ismn "979-0-2605-3211-3 12345" "includetext guardwhitespace"
run 0 issn "0311-175X 00 17" "includetext guardwhitespace"
run 0 code128 "Count01234567!" "includetext"
run 0 code128 "^0270123^027" "parse"
run 0 code128 "0123^0277890" "parse"
run 0 code128 "ABC^0270123" "parse"
run 0 code128 "Panam^225" "parse"
run 0 code128 "^FNC1890^^ABC" "parsefnc"  ## ESCAPED ^
run 0 code128 "^FNC3ABCD^FNC2" "parsefnc"
run 0 code128 "^104^102^016^017^033^034^035" "raw"
run 0 gs1-128 "(01)95012345678903(3103)000123" "includetext"
run 0 gs1-128 "(01)0061414199996(17)100101(10)123ABC(21)1234567890" ""
run 0 ean14 "(01) 0 46 01234 56789 3" "includetext"
run 0 sscc18 "(00) 0 0614141 123456789 0" "includetext"
run 0 sscc18 "(00)00614141123456789" "includetext"
run 0 code39 "THIS IS CODE 39" "includetext hidestars"
run 0 code39 "THIS IS CODE 39" "includetext includecheck includecheckintext"
run 0 code39 "THIS IS CODE 39Q" "includetext includecheck validatecheck hidestars"
run 1 code39 "ABCa0123" ""  ## ERROR bad character
run 1 code39 "THIS IS CODE 39R" "includecheck validatecheck" ## ERROR bad check
run 0 code39ext "Code39 Ext!" "includetext includecheck includecheckintext"
run 0 code32 "01234567" "includetext"
run 0 pzn "123456" "includetext"
run 0 code93 "THIS IS CODE 93" "includetext includecheck"
run 0 code93ext "Code93 Ext!" "includetext includecheck"
run 0 interleaved2of5 "2401234567" "height=0.5 includecheck includetext includecheckintext"
run 0 itf14 "0 46 01234 56789 3" "includetext"
run 0 itf14 "0460123456789" "includetext"
run 0 identcode "563102430313" "includetext"
run 0 leitcode "21348075016401" "includetext"
run 0 databaromni "(01)24012345678905" ""
run 0 databarstacked "(01)24012345678905" ""
run 0 databarstackedomni "(01)24012345678905" ""
run 0 databartruncated "(01)24012345678905" ""
run 0 databarlimited "(01)15012345678907" ""
run 0 databarexpanded "(01)95012345678903(3103)000123" ""
run 0 databarexpandedstacked "(01)95012345678903(3103)000123" "segments=4"
run 0 pharmacode "117480" "showborder"
run 0 pharmacode2 "117480" "includetext showborder"
run 0 code2of5 "01234567" "includetext"
run 0 code2of5 "01234567" "includetext includecheck includecheckintext"
run 0 code2of5 "012345670" "includetext includecheck validatecheck"
run 1 code2of5 "01234567A" ""  ## ERROR bad char
run 1 code2of5 "012345671" "validatecheck"  ## ERROR bad check
run 0 industrial2of5 "01234567" "includetext includecheck includecheckintext"
run 0 iata2of5 "01234567" "includetext includecheck includecheckintext"
run 0 matrix2of5 "01234567" "includetext includecheck includecheckintext"
run 0 coop2of5 "01234567" "includetext includecheck includecheckintext"
run 0 datalogic2of5 "01234567" "includetext includecheck includecheckintext"
run 0 code11 "0123456789" "includetext includecheck includecheckintext"
run 0 bc412 "BC412" "semi includetext includecheckintext"
run 0 rationalizedCodabar "A0123456789B" "includetext includecheck includecheckintext"
run 0 onecode "0123456709498765432101234567891" "barcolor=FF0000"
run 0 postnet "01234" "includetext includecheckintext"
run 0 planet "01234567890" "includetext includecheckintext"
run 0 royalmail "LE28HS9Z" "includetext includecheckintext"
run 0 royalmail "LE28HS9Z9" "includetext validatecheck"
run 1 royalmail "LE28HS9ZA" "includetext validatecheck" ## ERROR bad check
run 0 auspost "1156439111ABA 9" "includetext custinfoenc=character"
run 0 auspost "4556439111ABA 9" "includetext custinfoenc=character"
run 0 auspost "5956439111ABA 9" "includetext custinfoenc=character"
run 0 auspost "6256439111234567890123456" "includetext custinfoenc=numeric"
run 0 kix "1231FZ13XHS" "includetext"
run 0 japanpost "6540123789-A-K-Z" "includetext includecheckintext"
run 0 msi "0123456789" "includetext includecheck includecheckintext"
run 0 msi "0123456789" "includetext includecheck checktype=mod11"
run 0 msi "0123456789" "includetext includecheck checktype=mod1010"
run 0 msi "0123456789" "includetext includecheck checktype=mod1110"
run 0 msi "0123456789" "includetext includecheck checktype=ncrmod11"
run 0 msi "0123456789" "includetext includecheck checktype=ncrmod1110"
run 0 plessey "01234ABCD" "includetext includecheckintext"
run 0 telepen "ABCDEF" "includetext"
run 0 telepennumeric "01234567" "includetext"
run 0 posicode "ABC123" "version=b inkspread=-0.5 parsefnc includetext"
run 0 codablockf "CODABLOCK F 34567890123456789010040digit" "columns=8"
run 0 code16k "Abcd-1234567890-wxyZ" ""
run 0 code49 "MULTIPLE ROWS IN CODE 49" ""
run 0 channelcode "3493" "height=0.5 includetext "
run 0 flattermarken "11099" "inkspread=-0.25 showborder borderleft=0 borderright=0"
run 0 raw "331132131313411122131311333213114131131221323" "height=0.5"
run 0 daft "FATDAFTDAD" ""
run 0 symbol "fima" ""
run 0 symbol "fimb" ""
run 0 symbol "fimc" ""
run 0 symbol "fimd" "backgroundcolor=DD000011"
run 1 symbol "fime" ""	## ERROR unknown symbol
run 0 pdf417 "This is PDF417" "columns=2"
run 0 pdf417compact "This is compact PDF417" "columns=2"
run 0 micropdf417 "MicroPDF417" ""
run 0 datamatrix "This is Data Matrix!" ""
run 0 datamatrixrectangular "1234" ""
run 0 qrcode "http://goo.gl/0bis" "eclevel=M"
run 0 qrcode "QR CODE 1234" "version=1 eclevel=L"
run 0 qrcode "QR CODE 1234" "version=2 eclevel=M"
run 0 qrcode "QR CODE 1234" "version=3 eclevel=Q"
run 0 qrcode "QR CODE 1234" "version=4 eclevel=H"
run 0 qrcode "QR Code" ""
run 0 qrcode "QR ^067ode" "parse"
run 0 qrcode "QR CODE 7890" "format=micro"
run 0 qrcode "QR CODE 7890" "format=any"
run 0 qrcode "QR CODE 7890" "format=full"
run 0 qrcode "QR CODE 7890" "format=micro eclevel=L"
run 0 qrcode "QR CODE 7890" "format=micro eclevel=M"
run 1 qrcode "QR CODE 7890" "format=micro eclevel=Q"	## raiseerror
run 0 microqrcode "1234" ""
run 0 maxicode "[)>^03001^02996152382802^029840^029001^0291Z00004951^029UPSN^02906X610^029159^0291234567^0291/1^029^029Y^029634 ALPHA DR^029PITTSBURGH^029PA^029^004" "mode=2 parse"

run 0 azteccode "This is Aztec Code" "format=full"
run 0 azteccode "This is ^065ztec Code" "parse"
run 0 azteccode "This is Aztec Code" "eclevel=1"
run 0 azteccode "This is Aztec Code" "eclevel=25"
run 0 azteccode "This is Aztec Code" "eclevel=50"
run 0 azteccode "This is Aztec Code" "eclevel=75"
run 0 azteccode "This is Aztec Code" "eclevel=99"

## The format=value is added to get branch coverage
run 0 azteccodecompact "1234" ""
run 0 azteccodecompact "1234" "format=compact"
run 0 aztecrune "0" ""
run 0 aztecrune "1" "format=rune"
## Only run these when exhaustive testing
for RUNE in {2..255} ; do
	run 9 aztecrune $RUNE ""
done

run 0 codeone "Code One" ""
run 0 hanxin "This is Han Xin" ""
run 0 dotcode "This is DotCode" "fast"
run 0 gs1-cc "(01)95012345678903(3103)000123" "ccversion=b cccolumns=4"
run 0 ean13composite "2112345678900|(99)1234-abcd" "includetext"
run 0 ean8composite "02345673|(21)A12345678" "includetext"
run 0 upcacomposite "416000336108|(99)1234-abcd" "includetext"
run 0 upcecomposite "00123457|(15)021231" "includetext"
run 0 databaromnicomposite "(01)03612345678904|(11)990102" ""
run 0 databarstackedcomposite "(01)03412345678900|(17)010200" ""
run 0 databarstackedomnicomposite "(01)03612345678904|(11)990102" ""
run 0 databartruncatedcomposite "(01)03612345678904|(11)990102" ""
run 0 databarlimitedcomposite "(01)03512345678907|(21)abcdefghijklmnopqrstuv" ""
run 0 databarexpandedcomposite "(01)93712345678904(3103)001234|(91)1A2B3C4D5E" ""
run 0 databarexpandedstackedcomposite "(01)00012345678905(10)ABCDEF|(21)12345678" "segments=4 "
run 0 gs1-128composite "(00)030123456789012340|(02)13012345678909(37)24(10)1234567ABCDEFG" "ccversion=c"
run 0 gs1datamatrix "(01)03453120000011(17)120508(10)ABCD1234(410)9501101020917" ""
run 0 gs1datamatrix "(01)02900001333399212v<t!6SWsA/KE^02991012A^0299296T7YI2b9zPMt8y9mU+m7wSUbpe6+7rMdHyo5MMd5h08V1skespIRxR1NUp3MjLP1qDnJikugL76w1Yktr+lHw==" ""
run 0 gs1datamatrixrectangular "(01)03453120000011(17)120508(10)ABCD1234(410)9501101020917" ""
run 0 gs1qrcode "(01)03453120000011(8200)http://www.abc.net(10)ABCD1234(410)9501101020917" ""
run 0 hibccode39 "A123BJC5D6E71" "includetext"
run 0 hibccode128 "A123BJC5D6E71" "includetext"
run 0 hibcdatamatrix "A123BJC5D6E71" ""
run 0 hibcdatamatrixrectangular "A123BJC5D6E71" ""
run 0 hibcpdf417 "A123BJC5D6E71" ""
run 0 hibcmicropdf417 "A123BJC5D6E71" ""
run 0 hibcqrcode "A123BJC5D6E71" ""
run 0 hibccodablockf "A123BJC5D6E71" ""
run 0 hibcazteccode "A123BJC5D6E71" ""

##
## END OF TEST CASES
##
echo 
echo "-----------------------"
echo "Number of tests: $NTESTS"
echo "Number of failures: $NFAILS"
echo "-----------------------"

